[package]
name = "minitask"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = { version = "2", default-features = false }
fastrand = "2"
futures-core = "0.3"
pin-project-lite = "0.2"

[dev-dependencies]
smol = "2"
